# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Conceito de X",
  "description": "Qual a diferenca do conceito de X para o de Y?"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/b3cc5213-6407-488a-b824-8cb8789304a4/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/b3cc5213-6407-488a-b824-8cb8789304a4/questions
Content-Type: application/json

{
  "question": "O que é Node.js e qual a sua diferenca quando comparado ao React.js?"
}
